#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Self-contained HTML -> XMind converter (no external files needed).

Supports HTML generated by `xmind-mobile-view` / `mindmap-html-authoring`,
which embed:

    const IMG = [...]
    const RAW_TREE = {...}

Usage:
    python html2xmind.py                       # convert every *.html next to this script
    python html2xmind.py a.html b.html         # convert specific files
    python html2xmind.py C:\\some\\folder        # convert every *.html under a folder (recursive)
    python html2xmind.py *.html                 # globs work too

Output .xmind is written next to each source .html.
This single file is fully standalone — drop it (with its .bat) anywhere.
"""

from __future__ import annotations

import base64
import glob
import json
import mimetypes
import re
import sys
import uuid
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any


MIME_EXTENSIONS = {
    "image/webp": ".webp",
    "image/png": ".png",
    "image/jpeg": ".jpg",
    "image/jpg": ".jpg",
    "image/gif": ".gif",
    "image/svg+xml": ".svg",
    "image/bmp": ".bmp",
}


@dataclass(frozen=True)
class ImageResource:
    index: int
    mime: str
    data: bytes
    path: str


def find_json_constant(source: str, name: str) -> Any:
    """Extract and parse a JSON object/array assigned to a JS const."""
    match = re.search(r"\bconst\s+" + re.escape(name) + r"\s*=", source)
    if not match:
        raise ValueError(f"Missing JavaScript constant: {name}")

    start = match.end()
    while start < len(source) and source[start].isspace():
        start += 1
    if start >= len(source) or source[start] not in "[{":
        raise ValueError(f"{name} is not assigned a JSON object or array")

    opener = source[start]
    closer = "]" if opener == "[" else "}"
    depth = 0
    in_string = False
    escape = False

    for pos in range(start, len(source)):
        char = source[pos]
        if in_string:
            if escape:
                escape = False
            elif char == "\\":
                escape = True
            elif char == '"':
                in_string = False
            continue

        if char == '"':
            in_string = True
        elif char == opener:
            depth += 1
        elif char == closer:
            depth -= 1
            if depth == 0:
                return json.loads(source[start : pos + 1])

    raise ValueError(f"Could not find the end of {name}")


def load_html_payload(html_path: Path) -> tuple[list[str], dict[str, Any]]:
    html = html_path.read_text(encoding="utf-8")
    images = find_json_constant(html, "IMG")
    tree = find_json_constant(html, "RAW_TREE")
    if not isinstance(images, list):
        raise ValueError("IMG must be a JSON array")
    if not isinstance(tree, dict):
        raise ValueError("RAW_TREE must be a JSON object")
    return images, tree


def extension_for_mime(mime: str) -> str:
    if mime in MIME_EXTENSIONS:
        return MIME_EXTENSIONS[mime]
    guessed = mimetypes.guess_extension(mime)
    return guessed or ".bin"


def decode_data_uri(uri: str, index: int) -> ImageResource:
    match = re.match(r"^data:([^;,]+)(;base64)?,(.*)$", uri, flags=re.S)
    if not match:
        raise ValueError(f"IMG[{index}] is not a data URI")

    mime = match.group(1).lower()
    is_base64 = bool(match.group(2))
    payload = match.group(3)
    if not is_base64:
        raise ValueError(f"IMG[{index}] is not base64 encoded")

    data = base64.b64decode(payload)
    ext = extension_for_mime(mime)
    return ImageResource(index=index, mime=mime, data=data, path=f"resources/img_{index:04d}{ext}")


def decode_images(image_uris: list[str]) -> dict[int, ImageResource]:
    resources: dict[int, ImageResource] = {}
    for index, uri in enumerate(image_uris):
        if not uri:
            continue
        resources[index] = decode_data_uri(uri, index)
    return resources


def topic_title(node: dict[str, Any]) -> str:
    return str(node.get("t") or "")


def to_xmind_topic(node: dict[str, Any], image_resources: dict[int, ImageResource]) -> dict[str, Any]:
    title = topic_title(node)
    topic: dict[str, Any] = {
        "id": str(node.get("i") or uuid.uuid4()),
        "class": "topic",
        "attributedTitle": [{"text": title}],
    }
    if title:
        topic["title"] = title

    image_index = node.get("p")
    if isinstance(image_index, int) and image_index in image_resources:
        image = image_resources[image_index]
        image_obj: dict[str, Any] = {"src": "xap:" + image.path}
        if "pw" in node:
            image_obj["width"] = node["pw"]
        if "ph" in node:
            image_obj["height"] = node["ph"]
        topic["image"] = image_obj

    link_target = node.get("lnk")
    if link_target:
        topic["href"] = "xmind:#" + str(link_target)

    children = node.get("c") or []
    if children:
        topic["children"] = {
            "attached": [to_xmind_topic(child, image_resources) for child in children]
        }

    return topic


def build_content_json(root_tree: dict[str, Any], image_resources: dict[int, ImageResource]) -> list[dict[str, Any]]:
    root_topic = to_xmind_topic(root_tree, image_resources)
    root_topic.setdefault("structureClass", "org.xmind.ui.logic.right")
    title = topic_title(root_tree) or "Recovered Mind Map"
    return [
        {
            "id": uuid.uuid4().hex[:26],
            "class": "sheet",
            "title": title,
            "rootTopic": root_topic,
        }
    ]


def build_metadata_json() -> dict[str, Any]:
    return {
        "dataStructureVersion": "2",
        "layoutEngineVersion": "3",
        "creator": {"name": "html-to-xmind", "version": "1.0.0"},
    }


def build_manifest_json(image_resources: dict[int, ImageResource]) -> dict[str, Any]:
    entries: dict[str, dict[str, Any]] = {
        "content.json": {},
        "metadata.json": {},
    }
    for image in image_resources.values():
        entries[image.path] = {}
    return {"file-entries": entries}


def write_xmind(
    output_path: Path,
    content: list[dict[str, Any]],
    metadata: dict[str, Any],
    manifest: dict[str, Any],
    image_resources: dict[int, ImageResource],
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("content.json", json.dumps(content, ensure_ascii=False, separators=(",", ":")))
        archive.writestr("metadata.json", json.dumps(metadata, ensure_ascii=False, separators=(",", ":")))
        for image in image_resources.values():
            archive.writestr(image.path, image.data)
        archive.writestr("manifest.json", json.dumps(manifest, ensure_ascii=False, separators=(",", ":")))


def convert_html_to_xmind(html_path: Path, output_path: Path) -> None:
    image_uris, raw_tree = load_html_payload(html_path)
    image_resources = decode_images(image_uris)
    content = build_content_json(raw_tree, image_resources)
    metadata = build_metadata_json()
    manifest = build_manifest_json(image_resources)
    write_xmind(output_path, content, metadata, manifest, image_resources)


def default_output_path(html_path: Path) -> Path:
    return html_path.with_suffix(".xmind")


def gather_html_files(args: list[str], script_dir: Path) -> list[Path]:
    files: list[Path] = []
    if not args:
        files.extend(sorted(script_dir.glob("*.html")))
    else:
        for raw in args:
            p = Path(raw)
            if p.is_dir():
                files.extend(sorted(p.rglob("*.html")))
            elif p.is_file():
                files.append(p)
            else:
                matched = [Path(m) for m in glob.glob(raw, recursive=True)]
                files.extend(sorted(m for m in matched if m.is_file()))

    seen: set[Path] = set()
    result: list[Path] = []
    for f in files:
        rp = f.resolve()
        if rp.suffix.lower() != ".html":
            continue
        if rp not in seen:
            seen.add(rp)
            result.append(f)
    return result


def main() -> int:
    script_dir = Path(__file__).resolve().parent
    html_files = gather_html_files(sys.argv[1:], script_dir)

    if not html_files:
        print("No .html files found to convert.")
        print("Drag HTML files onto the .bat, or place this next to your .html files and run it.")
        return 1

    ok = 0
    failed = 0
    for html in html_files:
        out = default_output_path(html)
        try:
            convert_html_to_xmind(html, out)
            print(f"[OK]   {html.name}  ->  {out.name}")
            ok += 1
        except Exception as exc:  # noqa: BLE001
            print(f"[FAIL] {html.name}  ({exc})")
            failed += 1

    print("-" * 48)
    print(f"Done. {ok} converted, {failed} failed, {len(html_files)} total.")
    return 0 if failed == 0 else 2


if __name__ == "__main__":
    sys.exit(main())
